### ISSUE TITLE
Bug: Not working on MacOS Sierra

### ISSUE THREAD

**Issue by stefanocoretta** [K8TIY/IPAPalette#1]
The palette is not working properly on MacOS Sierra 10.12.2. The palette window opens but symbols are not inserted in the text when clicked.

<img width="689" alt="screen shot 2016-12-25 at 23 26 00" src="https://cloud.githubusercontent.com/assets/6429302/21473080/842afb4e-caf9-11e6-97b4-860da0bd6f9b.png">

**Comment by 1ec5** [comment]
Works for me in macOS 10.12.2 (16C67).

**Comment by stefanocoretta** [comment]
I've also just tried to install on a new Mac with macOS 10.12.2 (16C67) with no success.

**Comment by jvradelis** [comment]
I have the same problem on macOS 10.12.3.  One can drag and drop the characters into an application, though.

**Comment by K8TIY** [comment]
There are a number of issues that should be solved for users of 10.12 through 10.15 and beyond, in the current (2.3 family) GitHub version if building from source. As should be apparent from the recent flurry of activity, I am preparing to release a version that has been thoroughly vetted on 10.15 and perhaps more importantly will be notarized by Apple.

**Comment by K8TIY** [comment]
Versions 2.3 and 2.3.1 were released specifically to address Catalina compatibility, so I am closing this.

**Comment by fenhl** [comment]
Unfortunately, it still doesn't work. Installing this leads to an error when trying to open the Keyboard preference pane.

**Comment by K8TIY** [comment]
Can you give me the text of the error?

**Comment by fenhl** [comment]
I'm no longer able to reproduce the error, the palette is working fine now.

**Comment by K8TIY** [comment]
Closing for now. There are other outstanding issues (like the issue of multiple "Show IPA Palette" entries in flag menu) but I believe this particular constellation of incompatibilities has been addressed in the 2.3.X family.
